### ISSUE TITLE
VHDX Capacity

### ISSUE THREAD

**Issue by yumiris** [yumiris/DietPi.Hyper-V#6]
This issue aims to discuss and decide on the maximum size of future VHDX images.

What capacity do you think the VHDX images should have and why? 80GB seems like a nice balance between stability, flexibility and nimbleness. However, it wouldn't be enough for a small media server. However, would people even store media in a VM? This is the kind of dilemma that inspired this post.

At the moment, the maximum capacity of the released images are **8GB**, though posts such as https://github.com/MichaIng/DietPi/issues/3559 hint at the capacity needing to be increased,.

---

When suggesting a capacity, please consider any technical caveats. Some (speculative) examples include:

- can DietPi handle a, say, 64TB VHDX?
- will there be any performance losses with increased disk capacity?
- will there be a hassle with administrating, backing up, cloning, etc.?

Ultimately, the decided capacity will need to be a balance between practicality and technicality.

The VHDX images are dynamic, which means that the capacity change won't affect their initial physical size. This means that the images can be set to have a maximum of size of entire terabytes without any impact on distribution and base system requirements. The releases will continue to remain nimble!

**Comment by Joulinar** [comment]
Hi,

well if there is more space needed on a VM, why not adding additional disks and move user data there. Like on all other SBC where people extend the system with external HDD/SDD 😃

**Comment by yumiris** [comment]
That's the recommended best practice, though having one VM disk can simplify the management of the data a lot. It also covers cases such as https://github.com/MichaIng/DietPi/issues/3559 😛

**Comment by jakebullet70** [comment]
I think 8GB is fine in most cases. But with that being said its a VHDX so there is no harm in making it larger.

I do store media in VM's. 

Also I ended up moving the dietpi_userdata to a new VHDX i added to the VM. It was easy with the diet_pi menu system. I would say if I would of known how easy it was I would not of tried to expand the file system in the first place and just added the new drive. 

I would say 40GB is fine and would cover most everything and  let people know about adding a 2nd drive and moving dietpi_userdata is an option. I did not see this option until I added the 2nd drive.

**Comment by MichaIng** [comment]
Isn't it possible to easily extend the size of the VHDX from within Hyper-V UI?
For our VMware and VirtualBox images we use 8 GiB because they can be extended quite easily. Of course one can as well always add another virtual drive, but the overhead of multiple drives is IMO not reasonable if all of them are virtual disk files on the same host disk anyway.

Generally in all cases where the virtual disk file size is dynamically allocated, there is not much reason to not make it larger, but one: It is (on WMware/VirtualBox) easy to increase the disk size (and expend partition + file system through e.g. dietpi-drive_manager) but it is not easy to decrease the size, e.g. if the host system has limited drive space and it hence must be assured that the VM does not eat up the host drive space, crashing both. This is the reason why we start with the relative small 8 GiB.

**Comment by yumiris** [comment]
@MichaIng

Hyper-V allows the resizing of VHDX images, though last time I tried messing around with sizes, I had to manually expand the ext4 partition (by booting a Linux ISO and using it to resize the partition on the VHDX image).

Indeed, it's certainly more difficult to decrease a VHDX, and a large VHDX comes with the risk of taking more space on the host which cannot be freed up. This is what contributes to the challenge of figuring the balance between a sizable VHDX and a manageable one.

---

Hmm, with what you and @jakebullet70 said, how would **80GB** sound? The VHDX images would still be released in ~120MB-160MB 7z archives, and would still initially consume around 2GB-3GB on the host. It's just that people would be able to store ~70GB of data on the images. It's 

Of course, that comes with the risk of having a VHDX that takes up 80GB on the host without being able to free up any space. But hmm... what are the odds of someone storing so much data on a VM without the host being a media/file server with a lot of capacity?

---

Psst, we can always release two images, one in 8GB and one in 80GB, but that might turn this over-thinking into over-engineering :p

**Comment by MichaIng** [comment]
@yumiris 
Yes, partition and file system need to be expended manually, however `dietpi-drive_manager` allows to do that as well, or you do the same with: `systemctl enable dietpi-fs_partition_resize` + reboot
Less safe but possible as well is to do it live:
```
sfdisk --no-reread /dev/sda -fN1 <<< ',+,,,' # Maximise partition size
partprobe /dev/sda # Make the kernel aware of the new size
partx -u /dev/sda # Failsafe, similar to partprobe
resize2fs -f /dev/sda1 # Extend file system until end of partition
```

**Comment by jakebullet70** [comment]
I think the problem (forgive me, not a Linux guy) was the swap partition was at the end of the image so while you can easily add to the drive size it would have to be a new partition (drive letter in Windows) Is it possible to put the swap partition at the beginning? 

80GB sounds fine and Hyper-V can shrink partitions but I will admit I have never tried it.
![part](https://user-images.githubusercontent.com/14124210/82820215-73a45580-9eaa-11ea-9846-b952a4d1d9c9.jpg)

**Comment by MichaIng** [comment]
Ah I see now that this is present on the base image. @yumiris any reason why adding a static swap partition instead of falling back to the swap file that is automatically created based on RAM size? Especially on a VM there should be no performance difference but a huge flexibility increase with a swap file.

Since your images are preinstalled, to achieve that you could do, prior to shutdown for image creation/conversion:
```
# Disable swapfile
/boot/dietpi/func/dietpi-set_swapfile 0

# Set swapfile to autosize, size will be so that there are 2 GiB total memory available, disabled if 2 GiB or more physical RAM are assigned
G_CONFIG_INJECT 'AUTO_SETUP_SWAPFILE_SIZE=' 'AUTO_SETUP_SWAPFILE_SIZE=1' /boot/dietpi.txt

# Switch install state so that on next boot the swapfile will be created base on dietpi.txt choices
echo 10 > /boot/dietpi/.install_stage
```
This will then be handled as pre-installed image which creates the swapfile according to dietpi.txt choices.

Another thing I recognised is that .hw_model is created, hence all systems from your images share the same internal UUID, hence e.g. their survey uploads and bug reports will override each other. I suggest you simply remove the file before image creation, it will be created on next boot with a fresh UUID:
```
rm /boot/dietpi/.hw_model
```

And last but not least, sorry for moving OOT:
Your images are Debian Bullseye (testing) I see. My production system is as well, however there is still much change on Bullseye (maaany APT package upgrades, deeper system design changes etc) and not all software titles are available/supported for now. Generally, especially for more inexperienced users I would recommend Buster until Bullseye has been released as new stable next summer.

**Comment by yumiris** [comment]
@MichaIng 

Including instructions certainly wouldn't hurt and like you've said, could even eliminate the need for changing the partition size of the release images.

The images derive from a standard Debian 10.1 installation, which by default set up a swap partition. 
Next image release will remove the swap partition in favour of DietPi's swap management. This also handles the scenario reported by @jakebullet70 

---

Regarding the UUID, good call - will remove the file before releasing the image.

Regarding the Debian version, which image have you checked and with what method? The latest one reports Buster when invoking `cat /etc/os-release`:

![image](https://user-images.githubusercontent.com/10241434/82881676-926e1f00-9f72-11ea-87ca-109e3853dc66.png)

**Comment by MichaIng** [comment]
> he images derive from a standard Debian 10.1 installation, which by default set up a swap partition.

Ah yeah that is true. Best is probably to manually create the partition table with single partition like described here: https://github.com/MichaIng/DietPi/wiki/How-to-create-a-DietPi-image-for-VMware

> Regarding the Debian version, which image have you checked and with what method?

Ignore the other points, I obviously forgot to add the mount point path when checking those files on a Bullseye host. Re-checked and all is fine, as well the `.hw_model` is not present as expected on a fresh image (compared to pre-installed one).

=> Nothing to do besides skipping swap partition creation during Debian installer, everything else is already perfectly fine. Sorry for confusion 😅.

**Comment by yumiris** [comment]
As of [`v7.00`](https://github.com/yumiris/DietPi.Hyper-V/releases/tag/v7.00):

- 8GB VHDX image
- one root ext4 partition
- discarded swap partition
