### ISSUE TITLE
Upgrading existing installation

### ISSUE THREAD

**Issue by holocronology** [yumiris/DietPi.Hyper-V#7]
Thoughts or comments on how to update an existing install?

**Comment by MichaIng** [comment]
Simply run `dietpi-update` to update the code base and all APT packages.

If you do not use the swap partition, I could give you some instructions on how to remove it, but actually it does not hurt and has some benefits over a swap file as well.

If you mean to upgrade from Debian Stretch to Debian Buster, here are the basic instructions:  https://dietpi.com/phpbb/viewtopic.php?p=18988#p18988
But keep in mind that some services might not start, e.g. when config settings or file format between the older and newer version had a breaking change, or such, hence if you have a free weekend, I'd always recommend setting up a fresh system instead of doing a Debian major version upgrade.

**Comment by yumiris** [comment]
@MichaIng 

Would it be a good idea to re-install major Debian versions then using `dietpi-backup` to restore the user data?

If someone:

1. backs up their DietPi on Stretch using `dietpi-backup`; then
1. conducts a fresh install of DietPi on Buster; then
2. restores the backup created earlier on Stretch...

Would there be any consequences?

**Comment by MichaIng** [comment]
Well, restoring the Stretch backup would restore the Stretch system. DietPi-Backup creates a full system backup, including all non-temporary files, so everything that defines whether it's Debian Stretch or Debian Buster 😉.

Another issue with such attempts is, since it does only backup/restore files on the filesystem, the partition table, filesystem metadata and bootloader are not included, which means that after restoring, the system would not boot without at least changing either the UUIDs of the partitions or recreating+flashing the bootloader (or on SBCs, adjusting the boot configs). With DietPi v7.0 we added the feature to restore a backup automatically on first boot, not for distro upgrades, which cannot work, but in case it broke to make restoring it quicker. While implementing it, we realised that the thing with the UUIDs is a deal-breaker for it, since a newly downloaded DietPi image is not guaranteed to have the same UUIDs as the image you used before. It was quite some effort to deal with this, so that when restoring a backup, it is checked whether the UUIDs still match, and otherwise whether we know which boot configs to adjust or if grub needs to be re-created: https://github.com/MichaIng/DietPi/blob/7d4181cbfced98a59dde84fd1f126f54aa5bc1dd/dietpi/dietpi-backup#L180-L281

**Comment by yumiris** [comment]
That's more powerful and thorough than anticipated; figured `dietpi-backup` merely backs up the user data, rather than absolutely everything. Hmm... will need to figure out a niftier strategy for upgrading major Debian releases.

**Comment by MichaIng** [comment]
`/mnt/dietpi_userdata`, respectively the drive it's on, can usually be move as is, but other userdata and configs e.g. in /etc and /var or the users home dirs need to be hand-selected as most of it is still system defaults or a product of system tools and might not be compatible with the next Debian version.

Distro upgrades following the instructions I linked above work mostly fine nowadays. Else I recommend a fresh install, migrate /mnt/dietpi_userdata first, install all required software titles freshly, many will use/migrate their data/configs from /mnt/dietpi_userdata. Then mount the rootfs of the old system and copy/migrate hand-selected data and configs from /var, /etc, /root, /home where manual changes have been done or related software obviously lost it.

**Comment by yumiris** [comment]
To settle:

- Upgrades can be done through `dietpi-update`;
- VHDX images will be released for every major of DietPi, i.e. 7, 8 ,etc.;
